name: Publish npm package

concurrency:
  group: "npm-publish"

on:
  push:
    branches:
      - release/*/*

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: ./.github/release-action
        with:
          # slack_access_token: "${{ secrets.SLACK_ACCESS_TOKEN }}"
          # slack_channel: "#npm-packages"
          npm_token: "${{ secrets.NPM_TOKEN }}"
